<?php
function getUrls ($sitemapAddr) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $sitemapAddr);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    $res = curl_exec($ch);
    curl_close($ch);
    echo $res;
    //return strip_tags($sitemapAddr);
}

function spellCheck ($url) {

}

function nutshell_post($params) {
    if (is_array($params) && !empty($params)) {
        // URL отправки запроса
        $url = 'https://app01.nutshell.com/api/v1/public/lead/87669:f872b73d597e6320f4a8018baba5ce5bf1b3bc68';

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)");
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($ch);
        curl_close($ch);
    } else {
        return false;
    }
}
$text = 'This XML file does not appear to have any style information associated with it. The document tree is shown below.
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://plastall.ru/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>always</changefreq>
<priority>1.0</priority>
</url>
<url>
<loc>https://plastall.ru/about/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>';
/*$text = 'This XML file does not appear to have any style information associated with it. The document tree is shown below.
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://plastall.ru/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>always</changefreq>
<priority>1.0</priority>
</url>
<url>
<loc>https://plastall.ru/about/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/about/news/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/about/diplomy/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/production/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/service/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/contacts/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/dilers/offer/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/world/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/delivery/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/certificates/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/recommendation/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/russia/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/moscow-store/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/belarus/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/ukraine/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/bulk-acrylic/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/nalivnoy_akril_plastall/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/bulk-acrylic/characteristics/naliv-plastall/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/bulk-acrylic/characteristics/naliv-plastall-super/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/bulk-acrylic/characteristics/naliv-plastall-black/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/anti-slip/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/dekotlaE5000/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/catalog/?type=1/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/bulk-acrylic/akril-sravnenie/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/bulk-acrylic/container-size/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/nalivnoy_akril_plastall_super/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/nalivnoy_akril_plastall_m/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/acrylic-liner/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/set-do-it-yourself/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/set-do-it-yourself/characteristics/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/catalog/?type=14/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/hitromaxcoatings/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/acrylic-liner/razmer/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/acrylic-liner/colors/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/floorok/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/fillerfloor/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/floorcoverings/fillerfloor/dekotlaE3300/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/set25/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/set40/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/floorcoverings/fillerfloor/dekotlaE2000/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/set40top/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/set25top/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/set15top/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/dekotla_top/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/floorcoverings/fillerfloor/epoxyprimer/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/3dfloor/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/floorcoverings/fillerfloor/dekotlalevel/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/floorcoverings/fillerfloor/dekotlaE7000/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/floorcoverings/fillerfloor/dekotlamortar/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/tools/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/floorcoverings/video/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/kazakhstan/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/hitroguard/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/hitroguard/polimochevina/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/instructions/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/instructions/bulk-acrylic/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/application-guidelines-acrylic-filler/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/means-to-prepare-baths/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/without/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/polish/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/instructions/acrylic-liner/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/how-to-install/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/acrylic-liner/zamer/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/instructions/other/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/instructions/set-do-it-yourself/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/instructions/recommendations-on-caring-for-bathroom/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>
https://plastall.ru/support/instruments-and-materials/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/video/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/video/lesson/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/how-to/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/set_video/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/account_video/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/video/other/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/acrylic-liner/video/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/video/other/voc/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/video/epoxy/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/epoksidniypol-video/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/warranty/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/reklama/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/faq/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/support/gallery/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/set-restoration/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/catalog/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/catalog_msk/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/catalog_spb/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/co-production/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/dilers/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/dilers/network/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/dilers/how/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/dilers/accounting/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/search/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/sitemap/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/mybuy/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/profile/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/mypassword/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/feedback/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/feedback/archive/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/production_ufa/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/production_perm/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/client/production_spb/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/question-form/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/forum/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/get-free-sample/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/payment/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/pribaltika/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/feedback/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/product/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/blog/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/ukraine2/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/akrilplastall/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/color_paste/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>
https://plastall.ru/product/view/clear_tool_for_bath/
</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/special_acrylic/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastall_super/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastallm/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/floor_ok_garage/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/hitromaxpa100/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/floor_ok_clear/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/hitromaxtop/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastall24diy/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastall24/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastallbeige/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastallmoscow/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastalldecor/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/pos_a5/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastall-titan/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastall-premium/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://plastall.ru/product/view/plastall-turbo/</loc>
<lastmod>2017-02-03</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
</urlset>';*/


//$u = 'http://xn--63-nmcpe.xn--p1ai/sitemap.xml';
//getUrls($u);
$text = explode("\n", strip_tags($text));
foreach ($text as $t) {
    if (strpos(trim($t),'http') !== false) {
        $urls[] = $t;
    }
}
$c = count($urls);
shell_exec('clear');
echo $c.' урлов в обнаружено'.PHP_EOL;
//shell_exec('LOGFILE=result.txt');
//shell_exec('exec 6>&1');         //  # Связать дескр. #6 со stdout.
                                //# Сохраняя stdout.
//shell_exec('exec > $LOGFILE');
$n = 0;
$yaresult = '';
$resultFile =  $argv[1];
foreach ($urls as $u) {
        $n++;
   //     shell_exec('touch result.txt');
  //      shell_exec('exec >result.txt');
        echo '-----'.PHP_EOL;
        echo "$n из $c: $u".PHP_EOL;
        `yaspeller $u 2>&1 | tee -a $resultFile`;
        //$yaresult = $yaresult.PHP_EOL;
    //$output = `ls -al`;
    //echo "<pre>$output</pre>";
}
echo PHP_EOL,"Results saved in $resultFile here: ";
echo `pwd`;
echo PHP_EOL,"spellCheck completed";
echo PHP_EOL;
//echo $yaresult;
//shell_exec('exec 1>&6 &6>&-');
?>